"use client";

import { motion } from 'framer-motion';
import { Zap, Repeat, Shield, Globe, Lock, Cpu } from 'lucide-react';
import { containerVars, itemVars } from "@/app/_lib/animations";

const mechanics = [
    {
        title: "Energy-backed Value",
        desc: "Each AMEV token is theoretically anchored to the energy yield produced by our ISC (Pichit) infrastructure, ensuring a tangible floor price.",
        icon: <Zap size={20} />,
        badge: "ISC Asset-backed"
    },
    {
        title: "Staking Governance",
        desc: "Stake your AMEV tokens to participate in network governance and earn a share of the ecosystem rewards generated by energy sales.",
        icon: <Lock size={20} />,
        badge: "Staking v1.0 Live"
    },
    {
        title: "REC Integration",
        desc: "AMEV tokens carry digital Renewable Energy Certificates (I-REC Standard), allowing holders to claim carbon offset verified on-chain.",
        icon: <Globe size={20} />,
        badge: "I-REC Compliant"
    },
    {
        title: "Continuous Deflation",
        desc: "A portion of the energy revenue is used to buy back and burn AMEV tokens from the open market, reducing total supply over time.",
        icon: <Repeat size={20} />,
        badge: "Buy-back & Burn"
    },
    {
        title: "Network Utility",
        desc: "AMEV is the native gas for the AMEV Ecosystem services, including P2P energy trading and smart meter management fees.",
        icon: <Cpu size={20} />,
        badge: "Native Ecosystem Utility"
    },
    {
        title: "Fully Audited",
        desc: "Our smart contracts and economic logic are rigorously audited by Tier-1 security firms to ensure maximum safety for all participants.",
        icon: <Shield size={20} />,
        badge: "CertiK & Hacken"
    }
];

export default function Utility() {
    return (
        <section className="bg-background py-22 px-6 lg:px-20 border-t border-border/5">
            <motion.div
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true }}
                variants={containerVars}
                className="max-w-7xl mx-auto"
            >
                {/* Header Section */}
                <div className="flex flex-col md:flex-row justify-between items-end gap-8 mb-20">
                    <motion.div variants={itemVars} className="max-w-xl">
                        <div className="flex items-center gap-3 mb-6">
                            <div className="flex items-center gap-3">
                                <motion.div
                                    initial={{ width: 0 }}
                                    whileInView={{ width: 32 }}
                                    className="h-[1px] bg-amber-deep"
                                />
                                <span className="font-brand text-[13px] tracking-[0.4em] uppercase text-amber-deep font-bold italic">
                                    Token Utility
                                </span>
                            </div>
                        </div>
                        <h2 className="text-4xl lg:text-5xl font-brand font-black italic text-text-main tracking-tighter leading-none">
                            How Token
                            <br/>
                            <span className="font-serif italic font-normal text-amber-deep">
                                works.
                            </span>
                        </h2>
                    </motion.div>
                    <motion.p variants={itemVars} className="max-w-[280px] text-md text-text-sub italic leading-relaxed text-right">
                        Three core properties make AMEV different from any other utility token in the market.
                    </motion.p>
                </div>

                {/* Grid Section */}
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                    {mechanics.map((item, idx) => (
                        <motion.div
                            key={idx}
                            variants={itemVars}
                            className="group p-10 rounded-[2.5rem] bg-panel-dark border border-panel-dark-border hover:border-amber transition-all duration-300 flex flex-col justify-between min-h-[320px]"
                        >
                            <div>
                                <div className="w-12 h-12 rounded-2xl bg-amber-tint flex items-center justify-center text-amber-deep mb-8 border border-amber-border group-hover:border-amber group-hover:scale-110 transition-all duration-300">
                                    {item.icon}
                                </div>
                                <h3 className="text-xl font-brand font-black italic text-panel-dark-text mb-4 tracking-tight">
                                    {item.title}
                                </h3>
                                <p className="text-sm text-panel-dark-muted leading-relaxed italic mb-8">
                                    {item.desc}
                                </p>
                            </div>

                            {/* Badge */}
                            <div className="w-fit px-4 py-2 rounded-xl bg-amber-tint border border-panel-dark-border">
                                <span className="text-[10px] font-mono font-bold uppercase tracking-widest text-amber-deep/60">
                                    {item.badge}
                                </span>
                            </div>
                        </motion.div>
                    ))}
                </div>
            </motion.div>
        </section>
    );
}